# Generated by Django 5.2.4 on 2025-07-31 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_book_isbn'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.RemoveField(
            model_name='note',
            name='created_at',
        ),
        migrations.AddField(
            model_name='note',
            name='author',
            field=models.CharField(default='0000000000000', max_length=100),
        ),
        migrations.AddField(
            model_name='note',
            name='isbn',
            field=models.CharField(default='0000000000000', max_length=13),
        ),
        migrations.AddField(
            model_name='note',
            name='publication_year',
            field=models.IntegerField(default=2023),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
